// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type District struct {
	Abbreviation *string `json:"abbreviation"`
	DisplayName  *string `json:"display_name"`
	Key          *string `json:"key"`
	Year         *int    `json:"year"`
}

type Robot struct {
	Year      *int    `json:"year"`
	RobotName *string `json:"robot_name"`
	Key       *string `json:"key"`
	TeamKey   *string `json:"team_key"`
}

type Team struct {
	Key               *string     `json:"key"`
	TeamNumber        *int        `json:"team_number"`
	Nickname          *string     `json:"nickname"`
	Name              *string     `json:"name"`
	SchoolName        *string     `json:"school_name"`
	City              *string     `json:"city"`
	StateProv         *string     `json:"state_prov"`
	Country           *string     `json:"country"`
	PostalCode        *string     `json:"postal_code"`
	Website           *string     `json:"website"`
	RookieYear        *int        `json:"rookie_year"`
	Motto             *string     `json:"motto"`
	YearsParticipated []int       `json:"years_participated"`
	Robots            []*Robot    `json:"robots"`
	Districts         []*District `json:"districts"`
}
